# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0002_auto_20180420_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dclxxb',
            name='xhm',
            field=models.CharField(default='', max_length=11, verbose_name='新号码'),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='dept',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='dept',
            field=models.ManyToManyField(default='', to='Myuser.dwxx', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
