# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0004_auto_20180531_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dept',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='dept',
            field=models.CharField(default='', max_length=11, verbose_name='部门'),
        ),
    ]
