# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0005_auto_20180531_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='dept',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='dept',
            field=models.ManyToManyField(default='', to='Myuser.dwxx', verbose_name='部门'),
        ),
    ]
