# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myuser', '0007_auto_20180531_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dclxxb',
            options={'permissions': (('cl', '处理'),), 'verbose_name': '待处理信息表', 'verbose_name_plural': '待处理信息表'},
        ),
    ]
